name: cellu
description: PPG센서를 활용하여 수집한 생체 데이터를 바탕으로 혈당 수치를 예측하는 애플리케이션
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_charts: ^0.5.2
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  http: ^0.13.3
  flutter_svg: ^2.0.9
  fl_chart: ^0.36.0
  flutter_dotenv: ^5.1.0
  local_auth: ^1.1.6
  logger: ^2.0.2+1
  provider: ^6.1.1
  flutter_time_picker_spinner: ^2.0.0
  shared_preferences: ^2.2.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/config/.env
    - assets/logo-small.svg

    - assets/img1.png
    - assets/img2.png
    - assets/img3.png
    - assets/img4.png
    - assets/img5.png
    - assets/img6.png
    - assets/img7.png
    - assets/img8.png
    - assets/img9.png
    - assets/img10.png
    - assets/img11.png