// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUa4OSS-205GSzgkLKRPmBSU7Nwc9nZUk',
    appId: '1:277912843609:web:823a2b7a67d3c200dfc848',
    messagingSenderId: '277912843609',
    projectId: 'flutter-8ebe9',
    authDomain: 'flutter-8ebe9.firebaseapp.com',
    storageBucket: 'flutter-8ebe9.appspot.com',
    measurementId: 'G-ZQD3WYDEXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk1xsGrbB3sXoZqQNZsHO-Dwl3W3UnLuo',
    appId: '1:277912843609:android:028486de0e1bba0bdfc848',
    messagingSenderId: '277912843609',
    projectId: 'flutter-8ebe9',
    storageBucket: 'flutter-8ebe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc51m7bOnjR7cW7KlCmULE9OJC9BviVtM',
    appId: '1:277912843609:ios:7ae026b76682a1d6dfc848',
    messagingSenderId: '277912843609',
    projectId: 'flutter-8ebe9',
    storageBucket: 'flutter-8ebe9.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc51m7bOnjR7cW7KlCmULE9OJC9BviVtM',
    appId: '1:277912843609:ios:f462ac45c1d32cc8dfc848',
    messagingSenderId: '277912843609',
    projectId: 'flutter-8ebe9',
    storageBucket: 'flutter-8ebe9.appspot.com',
    iosBundleId: 'com.example.flutterChat.RunnerTests',
  );
}
